# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 196abe1dbe704f2b12ed7d545b1524f5f07466270b051a0d37cadada3b15e3d61962839e78a3ea4caa614de1a59d39e63364ef0f7342fa0017d697cc2a22515a

test:
  secret_key_base: 4fb8a26dec726e883bcca16b843b94971b83fbccbdde2959e0b478b4107ab8605005f4e204878067a9acc5a955c17a077b321a4d0445725d4ff90dab261a1b74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
